FROM python:3.12-slim

WORKDIR /app

COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt

COPY quotes/ ./quotes/
COPY data/ ./data/

ENV REDIS_HOST="backend-redis"

EXPOSE 5000

CMD ["python", "quotes/quotes.py"]
